apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-loadbalancer
  namespace: odl-demo
  labels:
    app: kafka-ui
spec:
  selector:
    app: kafka-ui
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 10.64.140.44  # Kafka UI load balancer IP
