apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-loadbalancer
  labels:
    app: kafka-ui
spec:
  selector:
    app: kafka-ui
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.1.242  # Optional: specify a specific IP
