apiVersion: v1
kind: Service
metadata:
  name: mysql-loadbalancer
  namespace: odl-demo
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 10.64.140.43  # MySQL load balancer IP
