apiVersion: v1
kind: Service
metadata:
  name: mysql-loadbalancer
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.1.241  # Optional: specify a specific IP
