apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport
  namespace: odl-demo
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    nodePort: 30306
    protocol: TCP
  type: NodePort
