apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-ui
  labels:
    app: analytics-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-ui
  template:
    metadata:
      labels:
        app: analytics-ui
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: analytics-ui
        image: analytics-ui:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 3002
          hostPort: 3002
          protocol: TCP
        env:
        - name: PORT
          value: "3002"
        - name: AGGREGATION_SERVICE_URL
          value: "http://localhost:3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-ui
spec:
  selector:
    app: analytics-ui
  ports:
  - name: http
    port: 3002
    targetPort: 3002
  type: ClusterIP
