apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankui-landing
  labels:
    app: bankui-landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankui-landing
  template:
    metadata:
      labels:
        app: bankui-landing
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: bankui-landing
        image: bankui-landing:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 3004
          hostPort: 3004
          protocol: TCP
        env:
        - name: PORT
          value: "3004"
        - name: CUSTOMER_PROFILE_SERVICE_URL
          value: "http://customer-profile-service:3001"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bankui-landing
spec:
  selector:
    app: bankui-landing
  ports:
  - name: http
    port: 3004
    targetPort: 3004
  type: ClusterIP
