apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-profile-service
  labels:
    app: customer-profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-profile-service
  template:
    metadata:
      labels:
        app: customer-profile-service
    spec:
      containers:
      - name: customer-profile-service
        image: customer-profile-service:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 3001
        env:
        - name: CLUSTER1_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: cluster1-uri
        - name: CLUSTER2_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: cluster2-uri
        - name: PORT
          value: "3001"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: customer-profile-service
spec:
  selector:
    app: customer-profile-service
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  type: ClusterIP
