apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy-ui
  labels:
    app: legacy-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacy-ui
  template:
    metadata:
      labels:
        app: legacy-ui
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: legacy-ui
        image: legacy-ui:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 3003
          hostPort: 3003
          protocol: TCP
        env:
        - name: PORT
          value: "3003"
        - name: MYSQL_HOST
          value: "localhost"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "odl_user"
        - name: MYSQL_PASSWORD
          value: "odl_password"
        - name: MYSQL_DATABASE
          value: "banking"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: legacy-ui
spec:
  selector:
    app: legacy-ui
  ports:
  - name: http
    port: 3003
    targetPort: 3003
  type: ClusterIP
